# Lista blanca de urls que no necesitan autenticación JWT por GET y por POST
authentication:
   urlWhiteListByPost: [
        "/login"
   ]
   urlWhiteListByGet: [
        "/v2/api-docs",
        "/swagger-resources",
        "/swagger-resources/**",
        "/configuration/ui",
        "/configuration/security",
        "/swagger-ui.html",
        "/webjars/**",
        "/v3/api-docs/**",
        "/swagger-ui/**",
        "/login",
        "/public/videotecas",
        "/public/albumes"
  ]
# Propiedades configuración carpeta de backup de fotos y videos
backup:
   folder:
      album: /home/oscar/album
      video: /home/oscar/video